import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/case.dart';

class MedicalReportScreen extends StatelessWidget {
  final HeartCase heartCase;
  const MedicalReportScreen({required this.heartCase, super.key});

  Future<pw.Document> _generatePdf() async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.cairoRegular();
    final boldFont = await PdfGoogleFonts.cairoBold();

    pdf.addPage(
      pw.Page(
        theme: pw.ThemeData.withFont(base: font, bold: boldFont),
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(24),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Center(
                  child: pw.Text(
                    'Heart Disease Prediction Report',
                    style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
                  ),
                ),
                pw.SizedBox(height: 20),
                pw.Text('Patient ID: ${heartCase.id}'),
                pw.Text('Case Name: ${heartCase.name}'),
                pw.Text('Date: ${heartCase.timestamp.toString().substring(0, 16)}'),
                pw.Divider(),
                pw.SizedBox(height: 10),
                pw.Text(
                  'Result: ${heartCase.prediction == 0 ? 'No Disease' : 'Disease Detected'}',
                  style: pw.TextStyle(
                    fontSize: 18,
                    color: heartCase.prediction == 0 ? PdfColors.green : PdfColors.red,
                  ),
                ),
                pw.Text('Probability: ${(heartCase.probability * 100).toStringAsFixed(1)}%'),
                pw.SizedBox(height: 20),
                pw.Text('Clinical Features:', style: const pw.TextStyle(fontSize: 16)),
                ...heartCase.features.entries
                    .map((e) => pw.Text('${e.key.toUpperCase()}: ${e.value}')),
                pw.Spacer(),
                pw.Center(
                  child: pw.Text(
                    'This report is generated by Heart Predictor App',
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
    return pdf;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Medical Report')),
      body: PdfPreview(
        build: (format) => _generatePdf().then((pdf) => pdf.save()),
        allowSharing: true,
        allowPrinting: true,
        pdfFileName: '${heartCase.name}_report.pdf',
      ),
    );
  }
}